language: node_js
node_js: node
services:
- postgres
before_script:
- psql -c 'create database "test-restaurants-app";' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: Lm4mDDWYDSsGnJ/fIUGdiBHUngmTvl5bhVwxapE91xOfI6/J/z8F9t65sSZM1vec58JFDuvC3arjxTniPGTq0bpukkib7vrpq4276mT0K8px0YW7XsHWYSogVXaGwe5XRkjlf+qRxD5lvLr6NYKJ0NHKxQHbiHdQYFZSeM8uu+BbDvpLvOlaFw76nDkCqwoXO9jlwWd8BcaF55JjqLKRsjR2q5gYgGcEPRIh2l4s6FXO/ZNg89d1rWh6u44DuK6s8pVS5DgAunk9irOSj3ZA1tltNPKOyhPlf5Z/9Pwnor4WM8p4cf/Li01ENQsu0FSZqA/wxTVHcNMZiXMmQD8EXFv/Fm+blL73964dksCheudbVxG2FERm5sUEdCG7tgJHFZi/OGpeGT+tUaUMp1xfTU3uaMrRZjwcFOV9hFm2xtieBqwwHcWRaURmDPtpWbTDdWfmVcm74KnRrJP5DoQhTgdn3ErYLsfX7/pGXIWTVWNAxzXRkBD7Je1ldUq6CnUl9K9M9ZJjTta2Dg0TFPQWytDbTfBZlohmW859Mz6n5orkYCjBdn/CjqyTYZa1Y5A+9NHEbgKKfMQH64PuLIYEgWTqgPZU7caea+Psp7MtJdDVjPhA43EtQx106L10xLGrU72sld4scOGtSmcMH6W2ra1ogkn0Qbbx1bPm7ENOUr8=
  app: fast-headland-86765
  on:
    repo: Thinkful-Ed/node-restaurants-sequelize-tests
    branch: feature/travis-heroku
