language: node_js
node_js: node
services:
- postgres
before_script:
- psql -c 'create database "test-restaurants-app";' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: CRsUhMuDV/8G00Pm2AHjS8qeqQzXaN/w+kaXnHrXs3LRPggUaqGJTz5G0m5RPb6abK8UsPkgrfDQ2q8PFkWuAGu4bMnVJVZcBwemNEC7seEr5OdPJFBInSwn87rePmuIU2nehOmYQxFmIlLUb5h8iPOaN3aUKXd8/2T83dZw4TvjvKJ2l6p9zGCpHCRZUWp3UQBtFu9Q9akVTDwBkcjUEfx4MKzdyp67wFRCXMdFkp9oNBJlH05t6i+DmNg6YxnQzhnTJYG6TRgOfW9dOdFWT20Vdd7pBMbUEaJ0yAAeGEFH1dOsfX23T4XTk0877j/O8ip5HHtACGcswxUkVFCXVwJzVZprwrBTnHA8T0AjDKkLmIKLW7zUbvIXdnCK9vk+vqVT67I+kKj0kNkIbJMGcj1r7enpPpG/pkMw/WIhnOhGc4qpWBgkFtaKOQe+ZwfRsW/C8IN0M7WfU1jVLpyYRXKw3/udgrgSfYNIqpbhOZlg+cpOo205Gig7IZzv8d8It/zU0dXHC6RWuq5FwTBxhdL3YLYzJBKUzmQZB/V8FB/7TiyvIbAXt5K9MXdJ98EKxF3GTXtfD1xKKG4pmdwxZSEY97fRq6ZwzK6c1xw+JesIhSzvHYXZyVT0fpuv6vq9IFipGxOd3ugaKSh7DpnGjmy2fsvfzbFjVbjFyYpdZjo=
  app: lit-sea-98141
  on:
    repo: Ljyockey/node-restaurants-sequelize-tests
